import { useState, useEffect } from 'react'
import { GOLD, GOLD_DIM, GOLD_BDR, card, cardInner, lbl, inp, inputSt, pageStyle, pagePad, INK, BONE, SLATE, SLATE_L, SLATE_M, MUTED, GREEN, RED, FONT_BODY, FONT_DISPLAY, FONT_MONO } from './ds'


const LS_KEY_ANALYZE = 'adsoh_analyze_result'

function UrlInput() {
  const [unlocked, setUnlocked] = useState(false)
  const [accessCode, setAccessCode] = useState('')
  const [url, setUrl] = useState('')
  const [businessType, setBusinessType] = useState('')
  const [budget, setBudget] = useState('')
  const [goal, setGoal] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState(null)
  const [mismatch, setMismatch] = useState(null)
  const [copiedIndex, setCopiedIndex] = useState(null)
  const [fromCache, setFromCache] = useState(false)

  useEffect(() => {
    try { const s = localStorage.getItem(LS_KEY_ANALYZE); if (s) { setResult(JSON.parse(s)); setFromCache(true) } } catch {}
  }, [])

  const BACKEND = 'https://ai-ad-backend-zhpj.onrender.com'

  const loadJsPDF = () => new Promise(resolve => {
    if (window.jspdf) { resolve(window.jspdf.jsPDF); return }
    const script = document.createElement('script')
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'
    script.onload = () => resolve(window.jspdf.jsPDF)
    document.head.appendChild(script)
  })

  const downloadPDF = async () => {
    const jsPDF = await loadJsPDF()
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 20
    const maxWidth = pageWidth - margin * 2
    let y = 0
    const addPage = () => { doc.addPage(); y = 20 }
    const checkY = (needed = 10) => { if (y + needed > pageHeight - 20) addPage() }

    doc.setFillColor(8, 11, 18)
    doc.rect(0, 0, pageWidth, pageHeight, 'F')
    doc.setFillColor(99, 102, 241)
    doc.rect(0, 0, pageWidth, 4, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(28); doc.setFont('helvetica', 'bold')
    doc.text('AI Marketing Brain', pageWidth / 2, 80, { align: 'center' })
    doc.setFontSize(14); doc.setFont('helvetica', 'normal')
    doc.setTextColor(129, 140, 248)
    doc.text('AI Generated Marketing Report', pageWidth / 2, 95, { align: 'center' })
    doc.setDrawColor(99, 102, 241); doc.setLineWidth(0.5)
    doc.line(margin, 108, pageWidth - margin, 108)
    doc.setTextColor(200, 200, 200); doc.setFontSize(11)
    doc.text(`Business: ${result.url}`, pageWidth / 2, 125, { align: 'center' })
    doc.text(`Date: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, pageWidth / 2, 138, { align: 'center' })
    doc.setFontSize(10); doc.setTextColor(100, 116, 139)
    doc.text('Prepared by Adsoh | adsoh.com', pageWidth / 2, pageHeight - 25, { align: 'center' })
    doc.text('Confidential - For Client Use Only', pageWidth / 2, pageHeight - 15, { align: 'center' })
    doc.addPage(); y = 20

    result.analysis.split('\n').forEach(line => {
      if (!line.trim()) { y += 4; return }
      if (line.match(/^[A-Z\s()\/]+:$/)) {
        checkY(16); if (y > 25) y += 6
        doc.setFillColor(99, 102, 241); doc.rect(margin, y - 5, maxWidth, 10, 'F')
        doc.setTextColor(255, 255, 255); doc.setFontSize(9); doc.setFont('helvetica', 'bold')
        doc.text(line, margin + 4, y + 1); y += 12
        doc.setTextColor(50, 50, 50); doc.setFont('helvetica', 'normal')
      } else if (line.match(/^\d+\./)) {
        checkY(12)
        doc.setFillColor(245, 247, 250)
        const splitText = doc.splitTextToSize(line, maxWidth - 8)
        const boxH = splitText.length * 5 + 6
        doc.rect(margin, y - 4, maxWidth, boxH, 'F')
        doc.setDrawColor(200, 200, 220); doc.rect(margin, y - 4, maxWidth, boxH, 'S')
        doc.setTextColor(30, 30, 30); doc.setFontSize(9)
        doc.text(splitText, margin + 4, y + 1); y += boxH + 3
      } else {
        checkY(8); doc.setFontSize(9); doc.setTextColor(60, 60, 60); doc.setFont('helvetica', 'normal')
        const splitText = doc.splitTextToSize(line, maxWidth)
        doc.text(splitText, margin, y); y += splitText.length * 5 + 2
      }
    })
    doc.setFontSize(8); doc.setTextColor(150, 150, 150)
    doc.text('Generated by Adsoh', pageWidth / 2, pageHeight - 10, { align: 'center' })
    doc.save(`AI-Report-${result.url.replace(/https?:\/\//, '').replace(/\//g, '')}.pdf`)
  }

  async function runAnalyze(forceCategory) {
    setLoading(true); setError(null); setResult(null); setMismatch(null)
    try {
      const res = await fetch(`${BACKEND}/analyze`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url, business_type: forceCategory || businessType, budget: parseInt(budget), goal, force: !!forceCategory })
      })
      const data = await res.json()
      if (data.needs_confirmation) setMismatch(data.classification)
      else if (data.scan_failed) setError(data.message)
      else { setResult(data); localStorage.setItem(LS_KEY_ANALYZE, JSON.stringify(data)); setFromCache(false) }
    } catch { setError('Backend se connect nahi ho paya.') }
    setLoading(false)
  }

  function handleAnalyze() {
    if (!url || !businessType || !budget || !goal) { alert('Sabhi fields bharo pehle!'); return }
    runAnalyze(null)
  }

  const isMobile = window.innerWidth < 768
  const page = { minHeight: '100vh', background: INK, padding: isMobile ? '28px 16px' : '40px 36px', maxWidth: '820px', width: '100%', boxSizing: 'border-box' }

  // Password Screen
  if (!unlocked) return (
    <div style={{ minHeight: '100vh', background: INK, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '0 16px', boxSizing: 'border-box' }}>
      <div style={{ ...card, padding: '32px 24px', width: '100%', maxWidth: '320px', textAlign: 'center' }}>
        <div style={{ width: '48px', height: '48px', background: SLATE_M, borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 18px', fontSize: '22px' }}>🔐</div>
        <h2 style={{ color: BONE, fontSize: '16px', fontWeight: '600', margin: '0 0 6px' }}>AI Analyzer</h2>
        <p style={{ color: MUTED, fontSize: '13px', margin: '0 0 22px' }}>Access code daalo</p>
        <input type="password" value={accessCode} onChange={e => setAccessCode(e.target.value)}
          onKeyDown={e => { if (e.key === 'Enter') { if (accessCode === 'sohscape2024') setUnlocked(true); else alert('Wrong access code!') } }}
          placeholder="••••••••" style={{ ...inputSt, marginBottom: '10px', textAlign: 'center' }} />
        <button onClick={() => { if (accessCode === 'sohscape2024') setUnlocked(true); else alert('Wrong access code!') }}
          style={{ width: '100%', padding: '11px', borderRadius: '7px', border: 'none', background: '#171717', color: '#fff', fontSize: '14px', fontWeight: '600', cursor: 'pointer' }}>
          Unlock
        </button>
      </div>
    </div>
  )

  // Loading
  if (loading) return (
    <div style={page}>
      <h1 style={{ fontSize: '22px', fontWeight: '600', margin: '0 0 4px', letterSpacing: '-0.4px' }}>AI Analyzer</h1>
      <p style={{ color: MUTED, fontSize: '13px', margin: '0 0 32px' }}>Analyzing website...</p>
      <div style={{ ...card, padding: '40px', textAlign: 'center' }}>
        <p style={{ color: MUTED, fontSize: '14px', margin: '0 0 6px' }}>Website crawl ho rahi hai, strategy ban rahi hai...</p>
        <p style={{ color: MUTED, fontSize: '13px', margin: 0 }}>30–60 seconds lagenge</p>
      </div>
    </div>
  )

  // Mismatch
  if (mismatch) return (
    <div style={page}>
      <h1 style={{ fontSize: '22px', fontWeight: '600', margin: '0 0 4px', letterSpacing: '-0.4px' }}>AI Analyzer</h1>
      <p style={{ color: MUTED, fontSize: '13px', margin: '0 0 32px' }}>Category confirmation needed</p>
      <div style={{ maxWidth: '600px', width: '100%' }}>
        <div style={{ background: '#FFFBEB', border: '1px solid #FDE68A', borderRadius: '8px', padding: '18px 20px', marginBottom: '20px', display: 'flex', gap: '14px', alignItems: 'flex-start' }}>
          <span style={{ fontSize: '20px', flexShrink: 0 }}>⚠️</span>
          <div>
            <p style={{ margin: '0 0 5px', fontWeight: '600', fontSize: '15px', color: '#92400E' }}>Category Mismatch Detected</p>
            <p style={{ margin: 0, fontSize: '13px', color: '#78350F', lineHeight: '1.6' }}>
              Aapne <b>{mismatch.selected_category}</b> chuna, par website dekh ke yeh <b>{mismatch.recommended_category}</b> lag raha hai.
            </p>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: '10px', marginBottom: '18px' }}>
          {[['AI Detected', mismatch.recommended_category, GOLD], ['Confidence', `${mismatch.confidence_score}%`, '#22C55E']].map(([l, v, c]) => (
            <div key={l} style={{ ...card, padding: '14px 16px' }}>
              <p style={lbl}>{l}</p>
              <p style={{ margin: 0, fontSize: '15px', fontWeight: '600', color: c }}>{v}</p>
            </div>
          ))}
        </div>

        {mismatch.evidence?.length > 0 && (
          <div style={{ ...card, padding: '16px', marginBottom: '20px' }}>
            <p style={{ ...lbl, marginBottom: '10px' }}>Website Evidence</p>
            {mismatch.evidence.map((e, i) => <p key={i} style={{ margin: '0 0 5px', fontSize: '13px', color: MUTED, lineHeight: '1.5' }}>• {e}</p>)}
          </div>
        )}

        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          <button onClick={() => runAnalyze(mismatch.recommended_category)} style={{ width: '100%', padding: '13px', borderRadius: '8px', border: 'none', background: '#171717', color: '#fff', fontSize: '14px', fontWeight: '600', cursor: 'pointer' }}>
            Use AI Detected Category ({mismatch.recommended_category})
          </button>
          <button onClick={() => runAnalyze(mismatch.selected_category)} style={{ width: '100%', padding: '13px', borderRadius: '8px', border: `1px solid ${SLATE_L}`, background: 'transparent', color: MUTED, fontSize: '14px', fontWeight: '500', cursor: 'pointer' }}>
            Keep My Selection ({mismatch.selected_category})
          </button>
          <button onClick={() => setMismatch(null)} style={{ width: '100%', padding: '11px', borderRadius: '8px', border: 'none', background: 'transparent', color: MUTED, fontSize: '13px', cursor: 'pointer' }}>
            ← Edit Inputs
          </button>
        </div>
      </div>
    </div>
  )

  // Result
  if (result) {
    const lines = result.analysis.split('\n')
    return (
      <div style={page}>
        {fromCache && (
          <div style={{ background: SLATE_M, border: `1px solid ${SLATE_L}`, borderRadius: '7px', padding: '9px 16px', marginBottom: '16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <p style={{ margin: 0, fontSize: '12px', color: MUTED }}>Showing previous result · Generate new report to refresh</p>
            <button onClick={() => { localStorage.removeItem(LS_KEY_ANALYZE); setResult(null); setFromCache(false) }} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: '12px', color: MUTED, textDecoration: 'underline', padding: '0 2px' }}>Clear</button>
          </div>
        )}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '28px', flexWrap: 'wrap', gap: '12px' }}>
          <div>
            <h1 style={{ fontSize: '22px', fontWeight: '600', margin: '0 0 4px', letterSpacing: '-0.4px' }}>AI Analyzer</h1>
            <p style={{ color: MUTED, fontSize: '13px', margin: 0 }}>{result.url}{result.detected_category ? ` · ${result.detected_category}` : ''}</p>
          </div>
          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
            <button onClick={downloadPDF} style={{ background: '#22C55E', border: 'none', color: '#fff', padding: '7px 16px', borderRadius: '7px', fontSize: '13px', cursor: 'pointer', fontWeight: '600' }}>
              Download PDF
            </button>
            <button onClick={() => { localStorage.removeItem(LS_KEY_ANALYZE); setResult(null); setFromCache(false) }} style={{ background: 'transparent', border: `1px solid ${SLATE_L}`, color: MUTED, padding: '7px 16px', borderRadius: '7px', fontSize: '13px', cursor: 'pointer' }}>
              ← New Analysis
            </button>
          </div>
        </div>

        <div style={{ ...card, padding: '28px' }}>
          <h2 style={{ fontSize: '14px', fontWeight: '600', margin: '0 0 20px', color: GOLD }}>AI Generated Report</h2>
          {lines.map((line, i) => {
            if (line.match(/^[A-Z\s]+:$/) || line.match(/^[A-Z\s()]+:$/)) {
              return <h3 key={i} style={{ color: GOLD, fontSize: '12px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.08em', marginTop: '22px', marginBottom: '10px', paddingBottom: '6px', borderBottom: '1px solid #EAEAEA' }}>{line}</h3>
            }
            if (line.match(/^\d+\./)) {
              return (
                <div key={i} style={{ background: SLATE_M, border: `1px solid ${SLATE_L}`, borderRadius: '7px', padding: '10px 14px', marginBottom: '7px', fontSize: '14px', color: BONE, lineHeight: '1.5', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '10px' }}>
                  <span>{line}</span>
                  <button onClick={() => { navigator.clipboard.writeText(line.replace(/^\d+\.\s*/, '')); setCopiedIndex(i); setTimeout(() => setCopiedIndex(null), 1500) }}
                    style={{ background: copiedIndex === i ? '#22C55E' : '#F0F0F0', border: `1px solid ${SLATE_L}`, color: copiedIndex === i ? '#fff' : '#666', padding: '4px 10px', borderRadius: '5px', fontSize: '11px', cursor: 'pointer', flexShrink: 0, fontWeight: '600' }}>
                    {copiedIndex === i ? '✓' : 'Copy'}
                  </button>
                </div>
              )
            }
            if (line.trim()) return <p key={i} style={{ color: MUTED, fontSize: '14px', lineHeight: '1.6', margin: '4px 0' }}>{line}</p>
            return null
          })}
        </div>
      </div>
    )
  }

  // Main form
  return (
    <div style={page}>
      <h1 style={{ fontSize: '22px', fontWeight: '600', margin: '0 0 4px', letterSpacing: '-0.4px' }}>AI Analyzer</h1>
      <p style={{ color: MUTED, fontSize: '13px', margin: '0 0 32px' }}>Apni website URL daalo — AI real strategy banayega</p>

      <div style={{ maxWidth: '560px', width: '100%' }}>
        <div style={{ ...card, padding: isMobile ? '20px 16px' : '28px' }}>
          {error && <div style={{ background: 'rgba(196,69,58,0.10)', border: '1px solid #FECDD3', borderRadius: '7px', padding: '11px 14px', marginBottom: '20px', color: RED, fontSize: '13px' }}>{error}</div>}

          <div style={{ marginBottom: '18px' }}>
            <label style={lbl}>Website URL</label>
            <input type="url" value={url} onChange={e => setUrl(e.target.value)} placeholder="https://aapkibusiness.com" style={inputSt} />
          </div>

          <div style={{ marginBottom: '18px' }}>
            <label style={lbl}>Business Type</label>
            <select value={businessType} onChange={e => setBusinessType(e.target.value)} style={{ ...inputSt, color: businessType ? '#171717' : '#999' }}>
              <option value="">Select karo...</option>
              {['Wedding & Events','Restaurant / Cafe','Healthcare / Clinic','Real Estate','Education / Coaching','Retail Store','Salon / Spa','Travel & Tourism','Technology / SaaS','Digital Marketing Agency','Other'].map(o => <option key={o} value={o}>{o}</option>)}
            </select>
          </div>

          <div style={{ marginBottom: '18px' }}>
            <label style={lbl}>Monthly Ad Budget (₹)</label>
            <input type="number" value={budget} onChange={e => setBudget(e.target.value)} placeholder="10000" style={inputSt} />
            {budget && <p style={{ color: MUTED, fontSize: '12px', margin: '6px 0 0' }}>Daily budget: ₹{Math.round(parseInt(budget) / 30).toLocaleString()}</p>}
          </div>

          <div style={{ marginBottom: '28px' }}>
            <label style={lbl}>Marketing Goal</label>
            <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: '8px' }}>
              {['Lead Generation','Website Traffic','Brand Awareness','WhatsApp Inquiries','Sales / Revenue','App Downloads'].map(g => (
                <div key={g} onClick={() => setGoal(g)} style={{ padding: '10px 13px', borderRadius: '7px', border: `1px solid ${goal === g ? GOLD + '60' : '#E5E5E5'}`, background: goal === g ? GOLD + '08' : '#FAFAFA', color: goal === g ? '#171717' : '#999', fontSize: '13px', cursor: 'pointer', fontWeight: goal === g ? '500' : '400', transition: 'all 0.1s' }}>
                  {g}
                </div>
              ))}
            </div>
          </div>

          <button onClick={handleAnalyze} style={{ width: '100%', padding: '13px', borderRadius: '8px', border: 'none', background: '#171717', color: '#fff', fontSize: '14px', fontWeight: '600', cursor: 'pointer' }}>
            Run AI Analysis
          </button>
        </div>
      </div>
    </div>
  )
}

export default UrlInput
